---
kind: pipeline
type: docker
name: test-on-amd64

platform:
  arch: amd64

steps:
  - name: test
    image: node:alpine
    commands:
      - npm ci
      - npm test

---
kind: pipeline
type: docker
name: test-on-arm64

platform:
  arch: arm64

steps:
  - name: test
    image: node:alpine
    commands:
      - npm ci
      - npm test
